using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Xunit.Generators;

public abstract class XunitGenerator : IIncrementalGenerator
{
#if XUNIT_GENERATOR_CORE
	const string AssemblyName = "xunit.v3.core.aot.generators";
	const string BaseInitAttributeName = "global::Xunit.v3.EngineInitializationAttribute";
#elif XUNIT_GENERATOR_RUNNERCOMMON
	const string AssemblyName = "xunit.v3.runner.common.aot.generators";
	const string BaseInitAttributeName = "global::Xunit.Runner.Common.RunnerInitializationAttribute";
#else
#error Unknown generator assembly
#endif

	readonly string attributeNameBase;

	protected XunitGenerator()
	{
		attributeNameBase = GetType().Name;
		if (attributeNameBase.EndsWith("Generator", StringComparison.Ordinal))
			attributeNameBase = attributeNameBase.Substring(0, attributeNameBase.Length - 9);
	}

	protected void AddInitAttribute(
		SourceProductionContext context,
		XunitGeneratorResult result,
		string initialization)
	{
		if (result is null)
			return;

		var initAttributeName = $"{attributeNameBase}٠{result.SafeNameSuffix}";
		var namespaceSuffix = result.ProjectPath.ToCompilerSafeName();
		var source = $$"""
			// <auto-generated> This file has been auto generated by {{AssemblyName}}. </auto-generated>

			#nullable enable

			[assembly: global::Xunit.AutoGenerated._{{namespaceSuffix}}.{{initAttributeName}}]

			namespace Xunit.AutoGenerated._{{namespaceSuffix}} {
				[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
				internal class {{initAttributeName}} : {{BaseInitAttributeName}} {
					public override async global::System.Threading.Tasks.ValueTask InitializeAsync() {
						{{initialization}}
					}
				}
			}
			""";

		context.AddSource($"{initAttributeName}.g.cs", SourceText.From(source, Encoding.UTF8));
	}


	void IIncrementalGenerator.Initialize(IncrementalGeneratorInitializationContext context)
	{
		var projectPath =
			context
				.AnalyzerConfigOptionsProvider
				.Select((provider, _) => provider.GlobalOptions.TryGetValue("build_property.MSBuildProjectFullPath", out var projectPath) ? projectPath : string.Empty);

		var objectType =
			context
				.CompilationProvider
				.Select((provider, _) => provider.GetSpecialType(SpecialType.System_Object));

		Initialize(context, projectPath, objectType);
	}

	protected abstract void Initialize(
		IncrementalGeneratorInitializationContext context,
		IncrementalValueProvider<string> projectPath,
		IncrementalValueProvider<INamedTypeSymbol> objectType);
}
